spring:
  application:
    name: gym-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: vinepu21
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true

jwt:
  secret: fitnessAppSecretKey32SymbolsMinRequiredForHS256
  expiration: 900000        # 15 минут для accessToken
  refresh:
    expiration: 2592000000  # 30 дней для refreshToken (в миллисекундах)

logging:
  level:
    org.flywaydb: DEBUG