spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: vinepu21
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
logging:
  level:
    org.flywaydb: DEBUG